/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.aipim.miloopcuaclient;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {

	@Test
	public void appHasAGreeting() {}
}
